### PR TITLE
New template for Bootstrap 5

### PR DESCRIPTION
**Pull request by Kvaksrud**

### CODE REVIEW

**Comment by shengslogar** [comment]
Thanks for the PR. I'm hesitant to merge this in, since it's identical to the existing Bootstrap 4 template outside of the wrapping `<nav>`  element. Is there something I'm missing here?

https://github.com/diglactic/laravel-breadcrumbs/blob/7a4db9535cf656340ed1f148c5ff035b436e7731/resources/views/bootstrap4.blade.php#L1-L15

**Comment by shengslogar** [comment]
Actually, this matches the new Bootstrap 5 syntax. If you want to rename this to `breadcrumbs::bootstrap5`, I'll merge that in.

https://getbootstrap.com/docs/5.0/components/breadcrumb/

**Comment by Kvaksrud** [comment]
Renamed to Bootstrap 5 as it is based on it

**Comment by shengslogar** [comment]
Thanks. I deleted my last comment because I noticed the Bootstrap 4 spec was actually supposed to have the wrapping `<nav>` but it didn't make it into our `bootstrap4` template and I was thinking about consistency. We have wrapping elements in other templates, though, so this makes sense.

I'll merge this in and tag shortly. Thanks! 🚀

**Comment by Kvaksrud** [comment]
Thanks! :)

**Comment by shengslogar** [comment]
Tagged [v6.1.0](https://github.com/diglactic/laravel-breadcrumbs/releases/tag/v6.1.0)

**Pull request merged**
