### PR TITLE
Updated Laravel docs and api links to version 10.x

### PR DESCRIPTION
**Pull request by Rattone**
To always have the latest one and not have to update the readme every time

### CODE REVIEW

**Comment by Rattone** [comment]
@shengslogar Laravel API docs have "master" segment but it's for dev branch, there doesn't seem to be a url that sends to the latest version. I do a separate PR to update api links to version 10.x

**Comment by shengslogar** [comment]
Hmm, let's keep everything locked to 10.x then. Since laravel.com changes URLs occasionally, I'd rather we always check the URLs before each new major version to ensure nothing breaks. I'll have to update the [README](https://github.com/diglactic/laravel-breadcrumbs#new-version-of-laravel) with a note on this.

Please use the same PR, thanks.

**Comment by Rattone** [comment]
@shengslogar done!

**Comment by shengslogar** [comment]
Thank you!

**Pull request merged**
